#mqtt配置
com:
  mqtt:
    #url: tcp://192.168.3.181:1883
    url: tcp://47.111.136.160:1883
    clientId: mqtt_test123
    topics:
       door,doorswitch
    username: admin
    password: 123456
    timeout: 10
    keepalive: 20
    
